"""initial_schema

Revision ID: 03004a0e43a2
Revises: 
Create Date: 2026-04-17 12:57:26.129729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03004a0e43a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades_profondos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('responsable', sa.String(length=200), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividades_profondos_fecha'), 'actividades_profondos', ['fecha'], unique=False)
    op.create_table('categorias_gasto',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('fondos_parroquiales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('responsable', sa.String(length=200), nullable=True),
    sa.Column('dinero_recolectado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('entregado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('infancia', 'adolescencia', 'juventud', name='tipogrupoenum'), nullable=False),
    sa.Column('edad_minima', sa.Integer(), nullable=False),
    sa.Column('edad_maxima', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('items_inventario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('bueno', 'regular', 'danado', name='estadoitemenum'), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('responsable', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.Enum('formativo', 'liturgico', 'insumo', name='tipoitemenum'), nullable=True),
    sa.Column('origen', sa.Enum('compra', 'donacion', name='origenitemenum'), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otros_ingresos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otros_ingresos_fecha'), 'otros_ingresos', ['fecha'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('asesores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.Enum('base', 'coordinador', 'de_apoyo', 'de_contingencia', name='tipoasesorenum'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('efectivo', 'especie', name='tipodonacionenum'), nullable=False),
    sa.Column('actividad_id', sa.UUID(), nullable=True),
    sa.Column('donante', sa.String(length=200), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cantidad_especie', sa.Integer(), nullable=True),
    sa.Column('valor_estimado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('item_inventario_id', sa.UUID(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades_profondos.id'], ),
    sa.ForeignKeyConstraint(['item_inventario_id'], ['items_inventario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encuentros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=True),
    sa.Column('tema', sa.String(length=300), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('abierto', 'cerrado', name='estadoencuentroenum'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cerrado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encuentros_fecha'), 'encuentros', ['fecha'], unique=False)
    op.create_index(op.f('ix_encuentros_grupo_id'), 'encuentros', ['grupo_id'], unique=False)
    op.create_table('gastos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_gasto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_fecha'), 'gastos', ['fecha'], unique=False)
    op.create_index(op.f('ix_gastos_mes'), 'gastos', ['mes'], unique=False)
    op.create_table('log_acceso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('email_intento', sa.String(length=200), nullable=False),
    sa.Column('exitoso', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('registrado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos_actividad',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actividad_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('precio_venta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('es_donado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades_profondos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('rol', sa.Enum('administrador', 'asesor_grupo', 'asesor_tesoreria', 'asesor_tienda', 'observador', name='rolenum'), nullable=False),
    sa.Column('grupo_id', sa.UUID(), nullable=True),
    sa.Column('asignado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('asignado_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventas_dia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('registrado_por', sa.UUID(), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('total_calculado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_dia_fecha'), 'ventas_dia', ['fecha'], unique=False)
    op.create_table('asesor_grupo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asesor_id', sa.UUID(), nullable=False),
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asesor_id'], ['asesores.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuotas_asesor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asesor_id', sa.UUID(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('pagado', 'pendiente', name='estadocuotaenum'), nullable=False),
    sa.ForeignKeyConstraint(['asesor_id'], ['asesores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_venta_dia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('venta_dia_id', sa.UUID(), nullable=False),
    sa.Column('producto', sa.String(length=200), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['venta_dia_id'], ['ventas_dia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('miembros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('infancia', 'adolescencia', 'juventud', name='tipomiembroenum'), nullable=False),
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('telefono_personal', sa.String(length=20), nullable=True),
    sa.Column('nombre_acudiente', sa.String(length=200), nullable=True),
    sa.Column('telefono_acudiente', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ingresado_en_encuentro_id', sa.UUID(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['ingresado_en_encuentro_id'], ['encuentros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_miembros_grupo_id'), 'miembros', ['grupo_id'], unique=False)
    op.create_table('asistencia_encuentro',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('encuentro_id', sa.UUID(), nullable=False),
    sa.Column('miembro_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('asistio', 'no_asistio', 'justificado', name='estadoasistenciaenum'), nullable=False),
    sa.Column('registrado_por', sa.UUID(), nullable=True),
    sa.Column('registrado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encuentro_id'], ['encuentros.id'], ),
    sa.ForeignKeyConstraint(['miembro_id'], ['miembros.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistencia_encuentro_encuentro_id'), 'asistencia_encuentro', ['encuentro_id'], unique=False)
    op.create_index(op.f('ix_asistencia_encuentro_miembro_id'), 'asistencia_encuentro', ['miembro_id'], unique=False)
    op.create_table('historial_grupo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('miembro_id', sa.UUID(), nullable=False),
    sa.Column('grupo_anterior_id', sa.UUID(), nullable=False),
    sa.Column('grupo_nuevo_id', sa.UUID(), nullable=False),
    sa.Column('cambiado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('motivo', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['grupo_anterior_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['grupo_nuevo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['miembro_id'], ['miembros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_grupo')
    op.drop_index(op.f('ix_asistencia_encuentro_miembro_id'), table_name='asistencia_encuentro')
    op.drop_index(op.f('ix_asistencia_encuentro_encuentro_id'), table_name='asistencia_encuentro')
    op.drop_table('asistencia_encuentro')
    op.drop_index(op.f('ix_miembros_grupo_id'), table_name='miembros')
    op.drop_table('miembros')
    op.drop_table('detalle_venta_dia')
    op.drop_table('cuotas_asesor')
    op.drop_table('asesor_grupo')
    op.drop_index(op.f('ix_ventas_dia_fecha'), table_name='ventas_dia')
    op.drop_table('ventas_dia')
    op.drop_table('usuario_roles')
    op.drop_table('productos_actividad')
    op.drop_table('log_acceso')
    op.drop_index(op.f('ix_gastos_mes'), table_name='gastos')
    op.drop_index(op.f('ix_gastos_fecha'), table_name='gastos')
    op.drop_table('gastos')
    op.drop_index(op.f('ix_encuentros_grupo_id'), table_name='encuentros')
    op.drop_index(op.f('ix_encuentros_fecha'), table_name='encuentros')
    op.drop_table('encuentros')
    op.drop_table('donaciones')
    op.drop_table('asesores')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_otros_ingresos_fecha'), table_name='otros_ingresos')
    op.drop_table('otros_ingresos')
    op.drop_table('items_inventario')
    op.drop_table('grupos')
    op.drop_table('fondos_parroquiales')
    op.drop_table('categorias_gasto')
    op.drop_index(op.f('ix_actividades_profondos_fecha'), table_name='actividades_profondos')
    op.drop_table('actividades_profondos')
    # ### end Alembic commands ###
