"""add_fecha_nacimiento_to_asesores

Revision ID: 3a341fa86627
Revises: 03004a0e43a2
Create Date: 2026-04-17 18:41:32.366787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a341fa86627'
down_revision: Union[str, None] = '03004a0e43a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asesores', sa.Column('fecha_nacimiento', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asesores', 'fecha_nacimiento')
    # ### end Alembic commands ###
