"""add_log_reapertura_encuentro

Revision ID: 9fb7c0742a5c
Revises: fa108dbc8532
Create Date: 2026-04-18 09:50:40.477452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb7c0742a5c'
down_revision: Union[str, None] = 'fa108dbc8532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_reapertura_encuentro',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('encuentro_id', sa.UUID(), nullable=False),
    sa.Column('reabierto_por', sa.UUID(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('reabierto_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encuentro_id'], ['encuentros.id'], ),
    sa.ForeignKeyConstraint(['reabierto_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_reapertura_encuentro_encuentro_id'), 'log_reapertura_encuentro', ['encuentro_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_reapertura_encuentro_encuentro_id'), table_name='log_reapertura_encuentro')
    op.drop_table('log_reapertura_encuentro')
    # ### end Alembic commands ###
