"""add_estado_to_venta_dia

Revision ID: fa108dbc8532
Revises: 3a341fa86627
Create Date: 2026-04-18 09:37:41.074666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa108dbc8532'
down_revision: Union[str, None] = '3a341fa86627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas_dia', sa.Column('estado', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas_dia', 'estado')
    # ### end Alembic commands ###
